name: coverify
description: Search verified numbers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.5+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl:

  flutter_phone_direct_caller: ^2.0.0
  phonecallstate: ^1.0.1
  lazy_load_scrollview: ^1.3.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  http: ^0.13.3
  imei_plugin: ^1.2.0
  contacts_service: ^0.6.1
  permission_handler: ^7.1.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_white_bg.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android: true
  ios: true
  android_gravity: center

flutter:

  uses-material-design: true
  assets:
    - assets/images/
